#!/bin/zsh

zshrc_load_status 'key bindings'

bindkey -e
bindkey -s '^X^Z' '%-^M'
bindkey '^[e' expand-cmd-path
#bindkey -s '^X?' '\eb=\ef\C-x*'
bindkey '^[^I' reverse-menu-complete
bindkey '^X^N' accept-and-infer-next-history
bindkey '^[p' history-beginning-search-backward
bindkey '^[n' history-beginning-search-forward
bindkey '^[P' history-beginning-search-backward
bindkey '^[N' history-beginning-search-forward
bindkey '^w' kill-region-or-backward-word
bindkey '^W' kill-region-or-backward-word
bindkey '^I' complete-word
bindkey '^Xi' incremental-complete-word
bindkey '^[[1;5D' emacs-backward-word
bindkey '^[[1;5C' emacs-forward-word
bindkey "^[B"  backward-to-space
bindkey "^[F"  forward-to-space
bindkey "^[^b" backward-to-/
bindkey "^[^f" forward-to-/

if zmodload zsh/deltochar >&/dev/null; then
    bindkey '^[z' zap-to-char
    bindkey '^[Z' delete-to-char
fi

# Fix weird sequence that rxvt produces
bindkey -s '^[[Z' '\t'

bindkey -s '^|l' " | less"                           # c-| l  pipe to less
bindkey -s '^|g' ' | grep ""^[OD'                    # c-| g  pipe to grep
bindkey -s '^|a' " | awk '{print $}'^[OD^[OD"        # c-| a  pipe to awk
bindkey -s '^|s' ' | sed -e "s///g"^[OD^[OD^[OD^[OD' # c-| s  pipe to sed
bindkey -s '^|w' " | wc -l"                          # c-| w  pipe to wc

bindkey "^[[z3c" backward-kill-word
