;; -*- mode: emacs-lisp; auto-compile-lisp: nil; -*-

(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(Info-additional-directory-list (quote ("/usr/share/info" "~/info")))
 '(LaTeX-command-style (quote (("omega" "lambda") ("." "latex"))))
 '(LaTeX-section-label nil)
 '(LaTeX-verbatim-regexp "\\(verbatim\\*?\\|sigmalog\\)")
 '(Man-notify-method (quote bully))
 '(TeX-command-list (quote (("TeX" "tex '\\nonstopmode\\input %t'" TeX-run-TeX nil t) ("TeX Interactive" "tex %t" TeX-run-interactive nil t) ("LaTeX" "%l '\\nonstopmode\\input{%t}'" TeX-run-LaTeX nil t) ("LaTeX Interactive" "%l %t" TeX-run-interactive nil t) ("Omega" "lambda '\\nonstopmode\\input{%t}'" TeX-run-LaTeX nil "nil") ("Omega Interactive" "lambda %t" TeX-run-interactive nil "nil") ("LaTeX2e" "latex2e '\\nonstopmode\\input{%t}'" TeX-run-LaTeX nil t) ("View" "%v " TeX-run-silent t nil) ("Print" "%p %r " TeX-run-command t nil) ("Queue" "%q" TeX-run-background nil nil) ("File" "dvips %d -o %f " TeX-run-command t nil) ("BibTeX" "bibtex %s" TeX-run-BibTeX nil nil) ("Index" "makeindex %s" TeX-run-command nil t) ("Check" "lacheck %s" TeX-run-compile nil t) ("Spell" "<ignored>" TeX-run-ispell-on-document nil nil) ("Other" "" TeX-run-command t t) ("LaTeX PDF" "pdflatex '\\nonstopmode\\input{%t}'" TeX-run-LaTeX nil t) ("Makeinfo" "makeinfo %t" TeX-run-compile nil t) ("Makeinfo HTML" "makeinfo --html %t" TeX-run-compile nil t) ("AmSTeX" "amstex '\\nonstopmode\\input %t'" TeX-run-TeX nil t) ("Generate Preview" "See `preview-LaTeX-command'" TeX-inline-preview nil t))))
 '(add-log-keep-changes-together t)
 '(ange-ftp-ftp-program-args (quote ("-i" "-n" "-g" "-v" "-u")))
 '(auto-insert nil)
 '(auto-insert-mode nil nil (autoinsert))
 '(auto-insert-query (quote function))
 '(auto-revert-check-vc-info t)
 '(bbdb-complete-name-allow-cycling t)
 '(bbdb-dwim-net-address-allow-redundancy t)
 '(blink-cursor nil)
 '(browse-url-netscape-program "mozilla-firefox")
 '(c++-font-lock-extra-types (quote ("Q[a-zA-Z]*" "uint" "ulong" "string")))
 '(c-default-style (quote ((java-mode . "java") (other . "personal"))))
 '(calendar-week-start-day 1)
 '(canlock-password "86b712369f839f776688a36513969db03cf50eb2")
 '(case-fold-search t)
 '(column-number-mode t)
 '(compilation-ask-about-save nil)
 '(compilation-read-command t)
 '(compilation-scroll-output t)
 '(compilation-window-height 10)
 '(compile-command "make")
 '(custom-file "~/.emacs-cust")
 '(default-justification (quote left))
 '(desktop-save (quote if-exists))
 '(desktop-save-mode nil nil (desktop))
 '(dired-omit-files "^\\.?#\\|^\\.$")
 '(display-time-24hr-format t)
 '(display-time-day-and-date t)
 '(doxymacs-doxygen-style "JavaDoc")
 '(doxymacs-doxygen-tags "DOXYTAGS")
 '(ecb-auto-activate nil)
 '(ecb-compilation-buffer-names (quote (("*Calculator*") ("*vc*") ("*vc-diff*") ("*Backtrace*") ("*shell*") ("*eshell*") ("*compilation*") ("*bsh*") ("*grep*") ("*Compile-Log*"))))
 '(ecb-compile-window-height 10)
 '(ecb-compile-window-temporally-enlarge nil)
 '(ecb-enlarged-compilation-window-max-height 10)
 '(ecb-eshell-auto-activate t)
 '(ecb-eshell-enlarge-when-eshell nil)
 '(ecb-eshell-enlarge-when-selecting nil)
 '(ecb-eshell-fit-window-to-command-output nil)
 '(ecb-eshell-synchronize nil)
 '(ecb-layout-name "sigma")
 '(ecb-layout-window-sizes (quote (("sigma" (0.1761904761904762 . 0.8589743589743589) (0.19523809523809524 . 0.2564102564102564) (0.10476190476190476 . 0.3076923076923077) (0.09047619047619047 . 0.3076923076923077) (0.19523809523809524 . 0.2948717948717949)) ("left9" (0.1419753086419753 . 0.8225806451612904)))))
 '(ecb-major-modes-deactivate (quote (hide-all-except-activated . "\\(Info\\|custom\\)-mode")))
 '(ecb-options-version "2.31")
 '(ecb-other-window-behavior (quote only-edit))
 '(ecb-tip-of-the-day nil)
 '(ecb-vc-supported-backends (quote ((ecb-vc-dir-managed-by-CVS . vc-state) (ecb-vc-dir-managed-by-RCS . vc-state) (ecb-vc-dir-managed-by-SCCS . vc-state) (ecb-vc-dir-managed-by-SVN . vc-state))))
 '(enable-multibyte-characters t)
 '(eshell-ask-to-save-history (quote always))
 '(eshell-cmpl-cycle-completions nil)
 '(eshell-prefer-to-shell t nil (eshell))
 '(eshell-save-history-on-exit t)
 '(fill-column 79)
 '(fill-nobreak-predicate (quote (fill-french-nobreak-p fill-single-word-nobreak-p)))
 '(flyspell-default-dictionary "francais")
 '(flyspell-issue-welcome-flag nil)
 '(glasses-face (quote bold))
 '(glasses-separate-parentheses-p nil)
 '(glasses-separator "")
 '(global-font-lock-mode t nil (font-lock))
 '(global-hl-line-hack-mode t nil (hl-line-hack))
 '(global-semantic-decoration-mode t nil (semantic-decorate-mode))
 '(global-semantic-highlight-by-attribute-mode t nil (semantic-util-modes))
 '(global-semantic-highlight-edits-mode nil nil (semantic-util-modes))
 '(global-semantic-idle-scheduler-mode t nil (semantic-idle))
 '(global-semantic-show-parser-state-mode t nil (semantic-util-modes))
 '(global-semantic-show-tag-boundaries-mode t nil (semantic-util-modes))
 '(global-semantic-show-unmatched-syntax-mode nil nil (semantic-util-modes))
 '(global-semantic-stickyfunc-mode nil nil (semantic-util-modes))
 '(global-senator-minor-mode t nil (senator))
 '(global-visible-mark-mode-exclude-alist (quote ("^\\*")))
 '(gnus-cacheable-groups ".*")
 '(gnus-uncacheable-groups nil)
 '(gud-chdir-before-run nil)
 '(hl-line-hack-exceptions (quote ("*eshell*" "*Calendar*")))
 '(hl-line-hack-face (quote highlight))
 '(htmlize-head-tags "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">")
 '(htmlize-html-major-mode (quote html-mode))
 '(indent-tabs-mode nil)
 '(inhibit-startup-message t)
 '(line-number-mode t)
 '(log-edit-common-indent -7)
 '(mark-diary-entries-in-calendar t)
 '(max-lisp-eval-depth 500)
 '(max-specpdl-size 1000)
 '(mouse-avoidance-threshold 15)
 '(mouse-yank-at-point t)
 '(muse-colors-markup (quote (("\\b=[^
	 =>]" 61 muse-colors-verbatim) ("\\*+" 42 muse-colors-emphasized) ("^#title" 35 muse-colors-title) (muse-link-regexp 91 muse-colors-link))))
 '(muse-html-charset-default "utf-8")
 '(muse-html-encoding-default (quote utf-8))
 '(muse-latex-header "\\documentclass{article}

\\usepackage[english]{babel}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{hyperref}
\\usepackage[pdftex]{graphicx}

\\begin{document}

\\title{<lisp>(muse-publishing-directive \"title\")</lisp>}
\\author{<lisp>(muse-publishing-directive \"author\")</lisp>}
\\date{<lisp>(muse-publishing-directive \"date\")</lisp>}

\\maketitle

<lisp>(and muse-publish-generate-contents
	   \"\\\\tableofcontents
\\\\newpage\")</lisp>

")
 '(next-line-add-newlines nil)
 '(osd-args (quote ("--delay=3" "--age=3" "--pos=bottom" "--offset=70" "--outline=5" "--outlinecolour=grey" "--font=-microsoft-verdana-medium-r-normal--10-*-*-*-*-*-*")))
 '(paren-dont-load-timer nil)
 '(parens-require-spaces nil)
 '(partial-completion-mode t nil (complete))
 '(pcomplete-autolist t)
 '(pcomplete-cycle-completions nil)
 '(preview-default-option-list (quote ("displaymath" "floats" "graphics" "textmath" "footnotes")))
 '(prolog-system (quote swi))
 '(recentf-exclude (quote (":")))
 '(recentf-mode t nil (recentf))
 '(recentf-save-file "~/.emacs-recentf")
 '(reftex-plug-into-AUCTeX t t)
 '(save-place-limit 100)
 '(sawfish-extra-keyword-list (quote ("add-frame-style" "call-after-load" "call-after-property-changed" "call-after-state-changed" "custom-set-property" "define" "define-structure" "export" "open")))
 '(sawfish-warning-keyword-list (quote ("fixme" "FIXME" "Fixme" "fix me" "Fix me" "!!!" "Grrr" "Bummer" "todo" "TODO" "Todo")))
 '(scroll-bar-mode nil)
 '(semanticdb-default-file-name ".semantic.cache")
 '(semanticdb-default-save-directory "~/.semantic")
 '(semanticdb-global-mode t nil (semanticdb))
 '(show-paren-mode t nil (paren))
 '(speedbar-frame-parameters (quote ((width . 20) (border-width . 0) (menu-bar-lines . 0) (tool-bar-lines . 0) (unsplittable . t))))
 '(speedbar-use-images nil)
 '(tabbar-inhibit-functions (quote (tabbar-default-inhibit-function yh/tabbar-inhibit-function)))
 '(tc-make-attribution (quote kai-tc-simple-attribution))
 '(tc-mouse-overlays t)
 '(template-auto-insert nil)
 '(tempo-insert-region nil)
 '(tempo-interactive t)
 '(tool-bar-mode nil nil (tool-bar))
 '(tooltip-gud-tips-p t)
 '(tramp-default-method-alist (quote (("%" "" "smb") ("" "\\`\\(anonymous\\|ftp\\)\\'" "ftp") ("\\`ftp" "" "ftp") ("\\`localhost\\'" "\\`root\\'" "su"))))
 '(truncate-partial-width-windows nil)
 '(vc-follow-symlinks t)
 '(vc-make-backup-files t)
 '(view-diary-entries-initially t)
 '(visible-bell t)
 '(wdired-allow-to-change-permissions (quote advanced))
 '(which-function-mode nil nil (which-func)))

(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(bold ((t (:foreground "lightcoral" :weight bold))))
 '(bold-italic ((t (:foreground "orange" :slant italic :weight bold))))
 '(cparen-around-andor-face ((t (:foreground "red" :weight bold))))
 '(cparen-around-begin-face ((t (:foreground "red"))))
 '(cparen-around-define-face ((t (:foreground "lightblue" :weight bold))))
 '(cursor ((t (:background "yellow"))) t)
 '(dircolors-face-objet ((t (:foreground "Gray"))) t)
 '(ecb-default-highlight-face ((((class color) (background dark)) (:inherit ecb-default-general-face :background "slateblue"))))
 '(ecb-directory-face ((((class color) (background dark)) (:inherit ecb-default-highlight-face))))
 '(ecb-history-face ((((class color) (background dark)) (:inherit ecb-default-highlight-face))))
 '(ecb-method-face ((((class color) (background dark)) (:inherit ecb-default-highlight-face))))
 '(ecb-source-face ((((class color) (background dark)) (:inherit ecb-default-highlight-face))))
 '(ecb-token-header-face ((((class color) (background dark)) (:background "SeaGreen4"))))
 '(font-latex-bold-face ((t (:inherit bold))))
 '(font-latex-italic-face ((t (:inherit italic))))
 '(font-latex-math-face ((((class color) (background dark)) (:inherit font-lock-number-face))))
 '(font-latex-string-face ((((class color) (background dark)) (:inherit font-lock-string-face))))
 '(font-lock-builtin-face ((((class color) (min-colors 88) (background dark)) (:foreground "lightsteelblue"))))
 '(font-lock-comment-face ((((class color) (min-colors 88) (background dark)) (:foreground "gray"))))
 '(font-lock-doc-face ((t (:foreground "lightgreen"))))
 '(font-lock-floatnumber-face ((((class color) (background dark)) (:foreground "yellow4"))))
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background dark)) (:foreground "lightblue2"))))
 '(font-lock-hexnumber-face ((((class color) (background dark)) (:foreground "cyan"))))
 '(font-lock-number-face ((t (:foreground "yellow3"))))
 '(font-lock-pvs-function-type-face ((t (:foreground "blue"))))
 '(font-lock-pvs-parens-face ((t (:foreground "yellow"))))
 '(font-lock-pvs-record-parens-face ((t (:foreground "red"))))
 '(font-lock-pvs-set-brace-face ((t (:foreground "darkred"))))
 '(font-lock-pvs-table-face ((t (:foreground "black"))))
 '(font-lock-qt-face ((((class color) (background dark)) (:foreground "green2" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 88) (background dark)) (:foreground "green3"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue"))))
 '(gnus-group-mail-low-empty-face ((((class color) (background dark)) (:foreground "aquamarine3"))))
 '(gnus-group-mail-low-face ((t (:foreground "aquamarine3" :weight bold))))
 '(gnus-header-content-face ((t (:foreground "green" :slant italic))))
 '(gnus-header-name-face ((((class color) (background dark)) (:foreground "LightGreen"))))
 '(highlight ((((class color) (background dark) (type x)) (:background "slateblue")) (((class color) (background dark) (type nil)) (:background "blue"))))
 '(italic ((((supports :slant italic)) (:foreground "Orchid" :slant italic))))
 '(menu ((((type x-toolkit)) (:background "lightgrey" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(message-header-name-face ((((class color) (background dark)) (:foreground "green3"))))
 '(message-header-other-face ((((class color) (background dark)) (:foreground "#dd0000"))))
 '(mmm-code-submode-face ((t (:background "darkgreen"))))
 '(mmm-default-submode-face ((t (:background "black"))))
 '(mode-line ((t (:background "lightgrey" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(region ((t (:background "slategrey"))))
 '(show-paren-match-face ((t (:background "black" :foreground "red" :weight bold))))
 '(show-paren-mismatch-face ((t (:background "magenta" :foreground "white" :weight bold))))
 '(tabbar-default-face ((t (:inherit variable-pitch :background "gray72" :foreground "gray30" :height 0.8))))
 '(tabbar-selected-face ((t (:inherit tabbar-default-face :foreground "blue" :box (:line-width 2 :color "white" :style pressed-button)))))
 '(tabbar-unselected-face ((t (:inherit tabbar-default-face :box (:line-width 2 :color "white" :style released-button)))))
 '(underline ((t (:foreground "seagreen3" :underline t))))
 '(w3-style-face-00001 ((t (:underline nil :weight normal :height 150))))
 '(w3-style-face-00002 ((t (:underline nil))))
 '(w3-style-face-00003 ((t (:underline nil :weight normal :height 150))))
 '(w3-style-face-00004 ((t (:underline nil :weight normal :height 150))))
 '(w3-style-face-00005 ((t (:underline nil :height 150))))
 '(w3-style-face-00007 ((t (:underline nil :height 150))))
 '(w3-style-face-00008 ((t (:underline nil :weight normal :height 150)))))
