import os

elisp = Builder(action = '$EMACS $EFLAGS -f batch-byte-compile $SOURCE',
                suffix = '.elc',
                src_suffix = '.el')

loaddefs = Builder(action = """$EMACS $EFLAGS -eval '
                    (progn (load-library \"autoloads+\")
                      (let ((generated-autoload-file \"$SOURCE\"))
                        (create-directory-autoloads \".\")))'""",
                   src_suffix = '.el',
                   suffix = '.elc')

env = Environment(BUILDERS = {'Elisp' : elisp, 'Loaddefs' : loaddefs},
                  EMACS = '/Applications/Emacs.app/Contents/MacOS/Emacs',
                  EFLAGS = '-L custom -L lib -l ~/.emacs-local -batch',
                  ENV = os.environ)

SConscript(['custom/SConscript', 'config/SConscript', 'lib/SConscript'], exports='env')
