#!/bin/zsh

# Completions

zshrc_load_status 'completion system'

zstyle ':completion:*' completer _complete _prefix _ignored _complete:-extended

zstyle ':completion::prefix-1:*' completer _complete
zstyle ':completion:incremental:*' completer _complete _correct
zstyle ':completion:predict:*' completer _complete

zstyle ':completion:*:approximate-one:*'  max-errors 1
zstyle ':completion:*:approximate-four:*' max-errors 4

zstyle ':completion:*:complete-extended:*' matcher 'r:|[.,_-]=* r:|=*'

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path ~/.zsh/cache/$HOST

zstyle ':completion:*' expand 'yes'
zstyle ':completion:*' squeeze-slashes 'yes'

zstyle ':completion:*:complete:-command-::commands' ignored-patterns '*\~'

zstyle ':completion:*:*:*:users' ignored-patterns \
    adm apache bin daemon distccd games gdm haldaemon halt ident junkbust lp mail mailnull \
    messagebus named news nfsnobody nobody nscd ntp operator pcap postfix postgres radvd \
    rpc rpcuser rpm shutdown squid sshd sync uucp vcsa xfs

zstyle '*' single-ignored show

zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

zstyle ':completion:*:*:lpr:*' file-patterns '*.pdf *.ps *(-/)' '*:all-files'

zstyle ':completion:*:history-words' stop yes
zstyle ':completion:*:history-words' remove-all-dups yes
zstyle ':completion:*:history-words' list false
zstyle ':completion:*:history-words' menu yes

users=( yann yhodique sigma )
zstyle ':completion:*' users $users

: ${(A)_etc_hosts:=${(s: :)${(ps:\t:)${${(f)~~"$(</etc/hosts)"}%%\#*}##[:blank:]#[^[:blank:]]#}}}
: ${(A)_ssh_config_hosts:=${${${${(@M)${(f)"$(<$HOME/.ssh/config)"}:#Host *}#Host }:#*\**}:#*\?*}}

# this supposes you have "HashKnownHosts no" in your ~/.ssh/config
: ${(A)_ssh_known_hosts:=${${${(f)"$(<$HOME/.ssh/known_hosts)"}%%\ *}%%,*}}
: ${(A)_ssh_known_ips:=${${${(f)"$(<$HOME/.ssh/known_hosts)"}%%\ *}##*,}}

hosts=(
    "$_etc_hosts[@]"
    "$_ssh_config_hosts[@]"
    "$_ssh_known_hosts[@]"
    "$_ssh_known_ips[@]"
    )

zstyle ':completion:*' hosts $hosts

if which dircolors >&/dev/null && [[ -e "${zdotdir}/.colors" ]]; then
    eval "`dircolors -b $zdotdir/.colors`"
fi

zstyle ':completion:*' list-colors "$LS_COLORS"

zle -C all-matches complete-word _generic
zstyle ':completion:all-matches:*' old-matches only
zstyle ':completion:all-matches::::' completer _all_matches

zle -C force-menu menu-complete _generic
zstyle ':completion:force-menu:*' menu yes select

compdef _functions reload
compdef _users lh
compdef _typeset ts

compdef f=finger
compdef _workon v
compdef _workon v.switch

# pip zsh completion start
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip
# pip zsh completion end
